"""
Interface professionnelle et accessibilité : contrôles automatisés.

- aucun emoji utilisé comme icône ou libellé ;
- aucune esthétique décorative (dégradés, formes en pilule, ombres,
  transparences, animations) ;
- aucune mention « Made with AI » ou équivalente, aucun texte marketing ;
- aucune fausse métrique (valeur numérique codée en dur dans st.metric) ;
- contrastes suffisants et états jamais portés par la seule couleur ;
- libellés explicites pour les boutons et champs, un titre par page,
  adresses de pages stables (navigation déterministe).
"""

import ast
import re
import tomllib
from pathlib import Path

import pytest

from models.enums import NiveauAlerte, StatutDocument, StatutPeriode
from utils import ui_helpers
from utils.navigation import DEFINITION_BLOCS, toutes_les_entrees

RACINE = Path(__file__).resolve().parent.parent
PAGES = sorted((RACINE / "ui_pages").glob("*.py"))
SOURCES_INTERFACE = PAGES + [
    RACINE / "app.py",
    RACINE / "utils" / "session_auth.py",
    RACINE / "utils" / "navigation.py",
    RACINE / "utils" / "ui_helpers.py",
]
DOCUMENTS_INTEGRES = [
    RACINE / "docs" / nom
    for nom in ("guide_utilisateur.md", "guide_administrateur.md", "politique_confidentialite.md", "conditions_utilisation.md")
]

MOTIF_EMOJI = re.compile(
    "[\U0001F000-\U0001FAFF☀-➿⬀-⯿⏩-⏺▶◀️⃣]"
)


def _ids(chemin: Path) -> str:
    return str(chemin.relative_to(RACINE))


# ---------------------------------------------------------------------
# Icônes et identité
# ---------------------------------------------------------------------

@pytest.mark.parametrize("source", SOURCES_INTERFACE + DOCUMENTS_INTEGRES, ids=_ids)
def test_aucun_emoji_dans_l_interface(source):
    for numero, ligne in enumerate(source.read_text(encoding="utf-8").splitlines(), 1):
        assert not MOTIF_EMOJI.search(ligne), f"{_ids(source)}:{numero} contient un emoji : {ligne.strip()}"


def test_noms_de_blocs_sans_emoji_et_icones_d_une_bibliotheque_coherente():
    for nom_bloc in DEFINITION_BLOCS:
        assert not MOTIF_EMOJI.search(nom_bloc)
        assert nom_bloc[0].isalpha()
    for entree in toutes_les_entrees():
        assert re.fullmatch(r":material/[a-z_]+:", entree.icone), f"Icône non conforme : {entree.icone}"


def test_icones_de_page_link_conformes():
    for page in PAGES:
        for icone in re.findall(r'icon="([^"]*)"', page.read_text(encoding="utf-8")):
            assert re.fullmatch(r":material/[a-z_]+:", icone), f"{page.name} : icône {icone!r}"


# ---------------------------------------------------------------------
# Esthétique sobre
# ---------------------------------------------------------------------

MOTIFS_DECORATIFS = [
    r"linear-gradient", r"radial-gradient", r"backdrop-filter", r"box-shadow", r"@keyframes",
    r"animation\s*:", r"transition\s*:", r"999px", r"border-radius\s*:\s*50%",
    r"st\.balloons", r"st\.snow",
]


@pytest.mark.parametrize("source", SOURCES_INTERFACE + [RACINE / ".streamlit" / "config.toml"], ids=_ids)
def test_aucun_effet_decoratif(source):
    contenu = source.read_text(encoding="utf-8")
    for motif in MOTIFS_DECORATIFS:
        assert not re.search(motif, contenu), f"{_ids(source)} contient {motif}"


@pytest.mark.parametrize("source", SOURCES_INTERFACE, ids=_ids)
def test_arrondis_moderes(source):
    for valeur in re.findall(r"border-radius\s*:\s*([0-9.]+)(px|rem)", source.read_text(encoding="utf-8")):
        nombre, unite = float(valeur[0]), valeur[1]
        pixels = nombre * 16 if unite == "rem" else nombre
        assert pixels <= 6, f"{_ids(source)} : border-radius {valeur} trop arrondi"


def _config():
    with open(RACINE / ".streamlit" / "config.toml", "rb") as fichier:
        return tomllib.load(fichier)


def test_boutons_et_cartes_sans_forme_de_pilule():
    theme = _config()["theme"]
    for cle in ("baseRadius", "buttonRadius"):
        valeur = theme[cle]
        assert valeur not in ("full", "large"), f"{cle}={valeur}"
        assert re.fullmatch(r"[0-6]px", valeur), f"{cle}={valeur}"


def test_palette_sans_violet_ni_couleur_criarde():
    theme = _config()["theme"]
    for cle in ("primaryColor", "linkColor", "backgroundColor", "secondaryBackgroundColor", "textColor"):
        rouge, vert, bleu = _rgb(theme[cle])
        # Un violet a une composante rouge et bleue élevées et une composante verte faible.
        assert not (rouge > 120 and bleu > 120 and vert < 90), f"{cle} ressemble à un violet : {theme[cle]}"


# ---------------------------------------------------------------------
# Textes : ni tag « IA », ni marketing, ni remplissage
# ---------------------------------------------------------------------

MENTIONS_IA = [
    r"made with", r"built with", r"powered by", r"generated by", r"généré par (une )?ia",
    r"généré par l'ia", r"\bclaude\b", r"chatgpt", r"openai", r"anthropic",
]
FORMULES_MARKETING = [
    r"lorem ipsum", r"boostez", r"expérience moderne", r"intuitive?", r"simplifiée? au quotidien",
    r"tout ce dont vous avez besoin", r"en un clic", r"sereinement", r"plateforme complète",
    r"révolutionn", r"de nouvelle génération", r"sans effort",
]


@pytest.mark.parametrize("source", SOURCES_INTERFACE + DOCUMENTS_INTEGRES, ids=_ids)
def test_aucune_mention_ia_ni_formule_marketing(source):
    contenu = source.read_text(encoding="utf-8").lower()
    for motif in MENTIONS_IA + FORMULES_MARKETING:
        assert not re.search(motif, contenu), f"{_ids(source)} contient « {motif} »"


FAUX_CONTENUS = [
    r"témoignage", r"avis (des |de nos )?(clients|utilisateurs)", r"utilisateurs satisfaits",
    r"clients satisfaits", r"note moyenne", r"\bétoiles\b", r"certifié", r"certification",
    r"100 ?% conforme", r"partenaires?\b", r"références clients",
]


@pytest.mark.parametrize("source", SOURCES_INTERFACE + DOCUMENTS_INTEGRES, ids=_ids)
def test_aucun_faux_contenu(source):
    contenu = source.read_text(encoding="utf-8").lower()
    for motif in FAUX_CONTENUS:
        assert not re.search(motif, contenu), f"{_ids(source)} contient « {motif} »"


# ---------------------------------------------------------------------
# Métriques : uniquement des données réelles
# ---------------------------------------------------------------------

def _appels_metric(page: Path):
    for noeud in ast.walk(ast.parse(page.read_text(encoding="utf-8"))):
        if isinstance(noeud, ast.Call) and isinstance(noeud.func, ast.Attribute) and noeud.func.attr == "metric":
            valeur = noeud.args[1] if len(noeud.args) > 1 else next(
                (k.value for k in noeud.keywords if k.arg == "value"), None
            )
            yield noeud.lineno, valeur


@pytest.mark.parametrize("page", PAGES, ids=lambda p: p.name)
def test_aucune_fausse_metrique_codee_en_dur(page):
    for ligne, valeur in _appels_metric(page):
        if isinstance(valeur, ast.Constant):
            assert not isinstance(valeur.value, (int, float)), f"{page.name}:{ligne} métrique numérique codée en dur"
            assert not re.search(r"\d", str(valeur.value)), f"{page.name}:{ligne} métrique chiffrée codée en dur"


def test_tableau_de_bord_affiche_aucune_donnee_disponible_si_vide():
    contenu = (RACINE / "ui_pages" / "7_Tableau_de_Bord.py").read_text(encoding="utf-8")
    assert "Aucune donnée disponible." in contenu


# ---------------------------------------------------------------------
# Accessibilité : contrastes et états
# ---------------------------------------------------------------------

def _rgb(couleur):
    couleur = couleur.lstrip("#")
    return tuple(int(couleur[i:i + 2], 16) for i in (0, 2, 4))


def _luminance(couleur):
    def canal(c):
        c = c / 255
        return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4
    r, g, b = (canal(c) for c in _rgb(couleur))
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contraste(a, b):
    la, lb = sorted((_luminance(a), _luminance(b)), reverse=True)
    return (la + 0.05) / (lb + 0.05)


def test_contrastes_du_theme_au_moins_4_5():
    theme = _config()["theme"]
    couples = [
        (theme["textColor"], theme["backgroundColor"]),
        (theme["textColor"], theme["secondaryBackgroundColor"]),
        (theme["textColor"], _config()["theme"]["sidebar"]["backgroundColor"]),
        ("#FFFFFF", theme["primaryColor"]),
        (theme["linkColor"], theme["backgroundColor"]),
        (theme["primaryColor"], theme["backgroundColor"]),
    ]
    for texte, fond in couples:
        assert contraste(texte, fond) >= 4.5, f"Contraste insuffisant {texte} / {fond}"


@pytest.mark.parametrize("palette", [
    ui_helpers._COULEURS_STATUT_PERIODE, ui_helpers._COULEURS_NIVEAU_ALERTE, ui_helpers._COULEURS_STATUT_DOCUMENT,
], ids=["periodes", "alertes", "documents"])
def test_contrastes_des_badges_au_moins_4_5(palette):
    for etat, (texte, fond) in palette.items():
        assert contraste(texte, fond) >= 4.5, f"Badge {etat} : contraste {contraste(texte, fond):.2f}"


def test_badges_portent_toujours_un_libelle_textuel():
    for statut in StatutPeriode:
        html = ui_helpers.badge_statut_periode(statut)
        texte = re.sub(r"<[^>]+>", "", html).strip()
        assert len(texte) >= 3, f"Badge {statut} sans libellé"
    for niveau in NiveauAlerte:
        assert re.sub(r"<[^>]+>", "", ui_helpers.badge_niveau_alerte(niveau)).strip()
    for statut in StatutDocument:
        assert re.sub(r"<[^>]+>", "", ui_helpers.badge_statut_document(statut, "Libellé")).strip() == "Libellé"


# ---------------------------------------------------------------------
# Accessibilité : libellés, titres, navigation déterministe
# ---------------------------------------------------------------------

WIDGETS_A_LIBELLE = {
    "button", "form_submit_button", "download_button", "text_input", "number_input", "selectbox",
    "multiselect", "checkbox", "radio", "file_uploader", "text_area", "date_input", "toggle", "slider",
}


def _texte_de(noeud):
    if isinstance(noeud, ast.Constant) and isinstance(noeud.value, str):
        return noeud.value
    if isinstance(noeud, ast.JoinedStr):
        return "".join(v.value for v in noeud.values if isinstance(v, ast.Constant) and isinstance(v.value, str))
    return None


@pytest.mark.parametrize("source", SOURCES_INTERFACE, ids=_ids)
def test_widgets_ont_un_libelle_explicite(source):
    for noeud in ast.walk(ast.parse(source.read_text(encoding="utf-8"))):
        if not (isinstance(noeud, ast.Call) and isinstance(noeud.func, ast.Attribute)):
            continue
        if noeud.func.attr not in WIDGETS_A_LIBELLE:
            continue
        for mot_cle in noeud.keywords:
            if mot_cle.arg == "label_visibility":
                assert _texte_de(mot_cle.value) != "collapsed", f"{_ids(source)}:{noeud.lineno} libellé masqué"
        if not noeud.args:
            continue
        texte = _texte_de(noeud.args[0])
        if texte is None:  # libellé calculé (variable, expression) : vérifié à l'exécution
            continue
        assert len(re.findall(r"[A-Za-zÀ-ÿ]", texte)) >= 3 or isinstance(noeud.args[0], ast.JoinedStr), (
            f"{_ids(source)}:{noeud.lineno} libellé non explicite : {texte!r}"
        )


def test_champs_mot_de_passe_masques():
    for source in SOURCES_INTERFACE:
        for noeud in ast.walk(ast.parse(source.read_text(encoding="utf-8"))):
            if isinstance(noeud, ast.Call) and isinstance(noeud.func, ast.Attribute) and noeud.func.attr == "text_input":
                libelle = _texte_de(noeud.args[0]) if noeud.args else ""
                if libelle and "mot de passe" in libelle.lower():
                    types = [_texte_de(k.value) for k in noeud.keywords if k.arg == "type"]
                    assert types == ["password"], f"{_ids(source)}:{noeud.lineno} mot de passe non masqué"


@pytest.mark.parametrize("page", PAGES, ids=lambda p: p.name)
def test_chaque_page_a_un_titre_principal_unique(page):
    contenu = page.read_text(encoding="utf-8")
    nombre_titres = contenu.count("st.title(") + contenu.count("afficher_document(")
    assert nombre_titres == 1, f"{page.name} : {nombre_titres} titre(s) principal(aux)"


def test_adresses_de_pages_stables_et_uniques():
    adresses = [e.url_path for e in toutes_les_entrees() if not e.defaut]
    assert all(adresses), "Chaque page (hors page d'accueil) doit avoir une adresse fixe"
    assert len(adresses) == len(set(adresses))
    for adresse in adresses:
        assert re.fullmatch(r"[a-z]+(-[a-z]+)*", adresse), adresse


def test_donnees_exportables_depuis_les_pages_de_consultation():
    for nom in ("7_Tableau_de_Bord.py", "12_Rapports_Comptables.py", "16_Statistiques.py",
                "15_Notifications.py", "6_Bulletins_Paie.py", "13_Gestion_Documents.py"):
        assert "download_button" in (RACINE / "ui_pages" / nom).read_text(encoding="utf-8"), nom


def test_focus_clavier_visible():
    assert ":focus-visible" in (RACINE / "app.py").read_text(encoding="utf-8")


def test_aucun_lien_vers_l_ancien_dossier_pages():
    for page in PAGES:
        contenu = page.read_text(encoding="utf-8")
        assert '"pages/' not in contenu and "'pages/" not in contenu, page.name
